version: '2'
services:
  nginx-proxy:
    restart: always
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    environment:
      - DEFAULT_HOST=wellraum.com,www.wellraum.com
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    network_mode: bridge
  acme-companion:
    restart: always
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL="juancapoar@gmail.com"
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - "nginx-proxy"
    depends_on:
    - nginx-proxy
  wellraum-site:
    restart: always
    image: ghcr.io/sockshead/wellraum-landing:latest
    container_name: wellraum-site
    expose:
      - "8080"
    environment: 
    - VIRTUAL_HOST=wellraum.com,www.wellraum.com
    - LETSENCRYPT_HOST=wellraum.com,www.wellraum.com
    - VIRTUAL_PORT=8080
    - LETSENCRYPT_EMAIL=juancapoar@gmail.com
    depends_on:
    - nginx-proxy
    - acme-companion
volumes:
  conf:
  vhost:
  html:
  certs:
  acme: