services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/certs:/etc/nginx/certs
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d
      - /usr/share/nginx/html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d
      - /usr/share/nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock
  
  app:
    image: ghcr.io/sockshead/wellraum-landing:latest
    restart: unless-stopped
    ports:
      - 8080:80

  www:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - /app/dist
    environment:
      - VIRTUAL_HOST=wellraum.com,www.wellraum.com
      - LETSENCRYPT_HOST=wellraum.com,www.wellraum.com
      - LETSENCRYPT_EMAIL=juancapoar@gmail.com
    depends_on:
      - nginx-proxy
      - letsencrypt