version: '3'
services:
  wellraum-site:
    image: ghcr.io/sockshead/wellraum-landing:latest
    container_name: wellraum-site
    restart: always
    expose:
    - '8080'
    ports:
      - 8080:8080
    volumes:
      - app:/app/dist
  webserver:
    depends_on: 
    - wellraum-site
    image: nginx:latest
    container_name: webserver
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - app:/usr/share/nginx/html
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
volumes:
  app: