name: Build and deploy to Docker & DigitalOcean from develop branch

on:
  push:
    branches:
      - "develop"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build
      #- name: Login to GitHub Container Registry
      #  uses: docker/login-action@v1
      #  with:
      #    registry: ghcr.io
      #    username: ${{ github.repository_owner }}
      #    password: ${{ secrets.PAT }}
      #- name: Build image
      #  run: docker build . --file Dockerfile --tag wellraum-landing --label "run-number=${GITHUB_RUN_ID}"
      #- name: Push image
      #  run: |
      #    IMAGE_ID=ghcr.io/${{ github.repository_owner }}/wellraum-landing
      #    # Change all uppercase to lowercase
      #    IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
      #    docker tag wellraum-landing $IMAGE_ID:latest
      #    docker push $IMAGE_ID:latest
      #- name: Deploy Container to DigitalOcean
      #  uses: fifsky/ssh-action@master
      #  with:
      #    host: ${{ secrets.DO_HOST }}
      #    user: ${{ secrets.DO_USERNAME }}
      #    pass: ${{ secrets.DO_PASSWORD }}
      #    command: |
      #      echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
      #      IMAGE_ID=ghcr.io/${{ github.repository_owner }}/wellraum-landing
      #      # Change all uppercase to lowercase
      #      IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
      #      # Stop running container
      #      docker stop wellraum-landing
      #      # Remove old container
      #      docker rm wellraum-landing
      #      # Pull the Docker Image 
      #      docker pull $IMAGE_ID:latest
      #      # Run a new container from a new image
      #      docker run -it -d --restart unless-stopped -p 8080:80 --name wellraum-landing $IMAGE_ID:latest
